package com.htc.luminaos.utils;

import android.view.View;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;

import androidx.recyclerview.widget.RecyclerView;

import com.htc.luminaos.databinding.ActivityMainCustom2Binding;
import com.htc.luminaos.databinding.ActivityMainCustom3Binding;
import com.htc.luminaos.databinding.ActivityMainCustomBinding;
import com.youth.banner.Banner;

public class MainCustomBindingWrapper {
    public final View root;
    public RecyclerView shortcutsRv;
    public RelativeLayout rlEthernet;
    public RelativeLayout rlGoogle;
    public RelativeLayout rlSettings;
    public RelativeLayout rlUsb;
    public RelativeLayout rlHdmi1;
    public RelativeLayout rlWifi;
    public RelativeLayout rlBluetooth;
    public RelativeLayout rlClearMemory;
    public ImageView clearMemory;
    public RelativeLayout rlWallpapers;
    public ImageView wallpaper;
    public RelativeLayout homeEshare;
    public RelativeLayout homeNetflix;
    public RelativeLayout homeYoutube;
    public RelativeLayout homeDisney;
    public RelativeLayout rlUsbConnect;
    public ImageView usbConnect;
    public RelativeLayout rlNotice;
    public ImageView notice;
    public RelativeLayout rlSupport;
    public ImageView support;
    public RelativeLayout rlBattery;
    public ImageView battery;
    public ImageView homeBluetooth;
    public TextView timeTv;
    public ImageView homeEthernet;
    public ImageView homeWifi;
    public ImageView icon1;
    public ImageView icon2;
    public ImageView icon3;
    public ImageView icon4;
    public Banner gtvBanner;
    public ImageView eshareIcon;
    public ImageView hdmiIcon;
    public ImageView settingsIcon;
    public TextView eshareText;
    public TextView fileText;
    public TextView hdmiText;
    public TextView settingsText;
    public ImageView brand;
    public ActivityMainCustomBinding b1;
    public ActivityMainCustom2Binding b2;
    public ActivityMainCustom3Binding b3;
    public View icon1border;
    public View icon2border;
    public View icon3border;
    public View icon4border;
    public View icon5border;
    public View icon6border;
    public View icon7border;
    public View icon8border;

    public MainCustomBindingWrapper(ActivityMainCustomBinding b) {
        root = b.getRoot();
        shortcutsRv = b.shortcutsRv;
        rlEthernet = b.rlEthernet;
        homeEthernet = b.homeEthernet;
        rlGoogle = b.rlGoogle;
        rlSettings = b.rlSettings;
        rlUsb = b.rlUsb;
        rlHdmi1 = b.rlHdmi1;
        rlWifi = b.rlWifi;
        rlBluetooth = b.rlBluetooth;
        rlClearMemory = b.rlClearMemory;
        clearMemory = b.clearMemory;
        rlWallpapers = b.rlWallpapers;
        wallpaper = b.wallpaper;
        homeEshare = b.homeEshare;
        homeNetflix = b.homeNetflix;
        homeYoutube = b.homeYoutube;
        homeDisney = b.homeDisney;
        rlUsbConnect = b.rlUsbConnect;
        usbConnect = b.usbConnect;
        rlNotice = b.rlNotice;
        notice = b.notice;
        rlSupport = b.rlSupport;
        support = b.support;
        rlBattery = b.rlBattery;
        battery = b.battery;
        homeBluetooth = b.homeBluetooth;
        timeTv = b.timeTv;
        homeWifi = b.homeWifi;
        icon1 = b.icon1;
        icon2 = b.icon2;
        icon3 = b.icon3;
        icon4 = b.icon4;
        gtvBanner = b.gtvBanner;
        eshareIcon = b.eshareIcon;
        hdmiIcon = b.hdmiIcon;
        settingsIcon = b.settingsIcon;
        eshareText = b.eshareText;
        fileText = b.fileText;
        hdmiText = b.hdmiText;
        settingsText = b.settingsText;
        brand = b.brand;
        b1=b;
    }

    public MainCustomBindingWrapper(ActivityMainCustom2Binding b) {
        root = b.getRoot();
        shortcutsRv = b.shortcutsRv;
        rlEthernet = b.rlEthernet;
        homeEthernet = b.homeEthernet;
        rlGoogle = b.rlGoogle;
        rlSettings = b.rlSettings;
        rlUsb = b.rlUsb;
        rlHdmi1 = b.rlHdmi1;
        rlWifi = b.rlWifi;
        rlBluetooth = b.rlBluetooth;
        rlClearMemory = b.rlClearMemory;
        clearMemory = b.clearMemory;
        rlWallpapers = b.rlWallpapers;
        wallpaper = b.wallpaper;
        homeEshare = b.homeEshare;
        homeNetflix = b.homeNetflix;
        homeYoutube = b.homeYoutube;
        homeDisney = b.homeDisney;
        rlUsbConnect = b.rlUsbConnect;
        usbConnect = b.usbConnect;
        rlNotice = b.rlNotice;
        notice = b.notice;
        rlSupport = b.rlSupport;
        support = b.support;
        rlBattery = b.rlBattery;
        battery = b.battery;
        homeBluetooth = b.homeBluetooth;
        timeTv = b.timeTv;
        homeWifi = b.homeWifi;
        icon1 = b.icon1;
        icon2 = b.icon2;
        icon3 = b.icon3;
        icon4 = b.icon4;
        gtvBanner = b.gtvBanner;
        eshareIcon = b.eshareIcon;
        hdmiIcon = b.hdmiIcon;
        settingsIcon = b.settingsIcon;
        eshareText = b.eshareText;
        fileText = b.fileText;
        hdmiText = b.hdmiText;
        settingsText = b.settingsText;
        brand = b.brand;
        b2 = b;
        icon1border = b.icon1Border;
        icon2border = b.icon2Border;
        icon3border = b.icon3Border;
        icon4border = b.icon4Border;
    }

    public MainCustomBindingWrapper(ActivityMainCustom3Binding b) {
        root = b.getRoot();
        shortcutsRv = b.shortcutsRv;
        rlEthernet = b.rlEthernet;
        homeEthernet = b.homeEthernet;
        rlGoogle = b.rlGoogle;
        rlSettings = b.rlSettings;
        rlUsb = b.rlUsb;
        rlHdmi1 = b.rlHdmi1;
        rlWifi = b.rlWifi;
        rlBluetooth = b.rlBluetooth;
        rlClearMemory = b.rlClearMemory;
        clearMemory = b.clearMemory;
        rlWallpapers = b.rlWallpapers;
        wallpaper = b.wallpaper;
        homeEshare = b.homeEshare;
        homeNetflix = b.homeNetflix;
        homeYoutube = b.homeYoutube;
        homeDisney = b.homeDisney;
        rlUsbConnect = b.rlUsbConnect;
        usbConnect = b.usbConnect;
        rlNotice = b.rlNotice;
        notice = b.notice;
        rlSupport = b.rlSupport;
        support = b.support;
        rlBattery = b.rlBattery;
        battery = b.battery;
        homeBluetooth = b.homeBluetooth;
        timeTv = b.timeTv;
        homeWifi = b.homeWifi;
        icon1 = b.icon1;
        icon2 = b.icon2;
        icon3 = b.icon3;
        icon4 = b.icon4;
        gtvBanner = b.gtvBanner;
        eshareIcon = b.eshareIcon;
        hdmiIcon = b.hdmiIcon;
        settingsIcon = b.settingsIcon;
        eshareText = b.eshareText;
        fileText = b.fileText;
        hdmiText = b.hdmiText;
        settingsText = b.settingsText;
        brand = b.brand;
        b3 = b;
        icon1border = b.icon1Border;
        icon2border = b.icon2Border;
        icon3border = b.icon3Border;
        icon4border = b.icon4Border;
        icon5border = b.icon5Border;
        icon6border = b.icon6Border;
        icon7border = b.icon7Border;
        icon8border = b.icon8Border;
    }
}
